### ISSUE TITLE
Problem executing npm commands to deploy

### ISSUE THREAD

**Issue by KBaroni** [Azure/azure-iot-pcs-device-simulation#34]
# Type of issue 

- [ X] Bug
- [ ] New feature
- [ ] Enhancement

# Description 
I am attempting to deploy the IoT device simulation accelerator and am stuck with issues executing the npm commands in the deployment instructions.  I am new to npm so this could be user error.  Initially '_npm run deploy_' failed with an error about not finding tsc.  I installed tsc (_npm install -g typescript_) and then executed _tsc --init_.  I preserved the original tsconfig.json file and am now getting these errors when i execute _npm run deploy_: 

error TS2688: Cannot find type definition file for 'node'.

error TS2688: Cannot find type definition file for 'node-fetch'.

error TS2688: Cannot find type definition file for 'node-forge'.

error TS2688: Cannot find type definition file for 'tunnel'.

error TS2688: Cannot find type definition file for 'uuid'.

So, I'm stuck. 

...

# Steps to reproduce 

1. Bring up deployment folder in Visual Studio Code
2. Modify the parameters.json and add the config values
3. Run the command _npm install_ from the terminal window in VS Code.  It ran cleanly.
4. In the same window, run _npm run deploy_ and it generates the errors above. 

# Expected behavior 
This is my first time through but I expected resources to be allocated in Azure.  

# Current behavior 
npm run deploy generates the 5 errors noted above.  I can provide logs if it helps. 

# Known workarounds 
...

# Possible solution 
...

# Context and Environment
npm version: v15.5.1
OS: windows 10
Downloaded github code from here: https://github.com/Azure/azure-iot-pcs-device-simulation.git

**Comment by pratik11jain** [comment]
Hey, I do not have a repro on my side yet but I believe you can try the following to see if this fixes the issue
1) get the code from my PR -> https://github.com/Azure/azure-iot-pcs-device-simulation/pull/35
2) delete dist, node_modules folder
3) > npm ci
4) > npm run build

**Comment by KBaroni** [comment]
Thank you!  I made the changes you recommended above (including new package.json and package-lock.json) and accelerator is now deploying to Azure!!

**Comment by KBaroni** [comment]
Just ran into an issue with the _iot-device-simulation@1.0.0_ deploy script (`_npm run build && node ./dist/deploy.js_`) but it may not be an npm issue.  Would you prefer to keep this issue open or open a new issue?

**Comment by pratik11jain** [comment]
Can you open a different issue for this.. In the meantime, I will try running a deployment
