### ISSUE TITLE
Issue while deploying Azure IoT pcs device simulator

### ISSUE THREAD

**Issue by shivanjalikhare** [Azure/azure-iot-pcs-device-simulation#43]
# Type of issue 

- [ ] Bug
- [ ] New feature
- [ ] Enhancement

# Description 
I am trying to deploy the Azure IoT device simulation. I followed the mentioned instructions for visual basic deployment but I am getting errors while running "npm run deploy".  I also followed the steps from issue #34. But now i am getting this error on running "npm run deploy": 
...

# Steps to reproduce 

Bring up deployment folder in Visual Studio Code
Modify the parameters.json and add the config values
Run the command npm install from the terminal window in VS Code. It ran cleanly.
In the same window, run npm run deploy and it generates the errors above.

# Expected behavior 
...

# Current behavior 
src/aadApp.ts:49:9 - error TS2322: Type 'string | null | undefined' is not assignable to type 'string'.
  Type 'undefined' is not assignable to type 'string'.

49         return appCreationResponse.appId;
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/auth.ts:84:9 - error TS2322: Type 'null' is not assignable to type 'credentials'.

84         return null;
           ~~~~~~~~~~~~

src/auth.ts:108:13 - error TS2322: Type 'null' is not assignable to type 'credentials'.

108             return null;
                ~~~~~~~~~~~~

src/deploymentManager.ts:50:48 - error TS2345: Argument of type 'string | undefined' is not assignable to parameter of type 'string'.
  Type 'undefined' is not assignable to type 'string'.

50     await assignContributorRoleOnResourceGroup(rgResult.name, creds, sp.id, config);
                                                  ~~~~~~~~~~~~~

src/deploymentManager.ts:73:5 - error TS2322: Type 'string | null | undefined' is not assignable to type 'string'.
  Type 'undefined' is not assignable to type 'string'.

73     parameters.aadClientId.value = sp.appId;
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/deploymentManager.ts:75:5 - error TS2322: Type 'string | undefined' is not assignable to type 'string'.
  Type 'undefined' is not assignable to type 'string'.

75     parameters.aadClientServicePrincipalId.value = sp.id;
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/deploymentManager.ts:77:5 - error TS2322: Type 'string | undefined' is not assignable to type 'string'.
  Type 'undefined' is not assignable to type 'string'.

77     parameters.storageEndpointSuffix.value = creds.environment.storageEndpointSuffix;
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/deploymentManager.ts:113:58 - error TS2532: Object is possibly 'undefined'.

113         throw new Error(`Deployment validation failed: ${validationResponse.error.message}`);
                                                             ~~~~~~~~~~~~~~~~~~~~~~~~

src/deploymentManager.ts:133:62 - error TS2345: Argument of type 'string | undefined' is not assignable to parameter of type 'string'.
  Type 'undefined' is not assignable to type 'string'.

133     const lro = await client.deployments.beginCreateOrUpdate(rg.name, buildDeploymentName(config), deployment);
                                                                 ~~~~~~~

src/deploymentManager.ts:146:8 - error TS2454: Variable 'latestState' is used before being assigned.

146     if(latestState === 'Failed'){
           ~~~~~~~~~~~

src/deploymentManager.ts:149:35 - error TS2454: Variable 'latestState' is used before being assigned.

149         console.log(`Deployment ${latestState}.`);
                                      ~~~~~~~~~~~


Found 11 errors.

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! iot-device-simulation@1.0.0 build: `tsc`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the iot-device-simulation@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

# Known workarounds <!-- If any, please share here -->
...

# Possible solution <!-- If you have a suggestion, how the issue could be solved -->
...

# Context and Environment
npm version:
Windows 10
I downloaded the rep from github: https://github.com/Azure/azure-iot-pcs-device-simulation.git. 
* Operating System: ...
* Windows 10
* GitHub branch: ...
* .NET Runtime: ...
* 2.1.812

**Comment by peterfelts** [comment]
Would you please let me know the version of Node.js do you have installed? I'm running v15.5.1 on my machine.

Do you see any output that says "AAD application '<application name>' created..."?

It appears as if AAD application registration is failing without an exception being thrown.

**Comment by peterfelts** [comment]
Also, do you have permissions/authorization/privileges in your Azure subscription to create AAD application registrations? Perhaps this is an AAD auth issue and ADD is returning a warning/error message that the code should be catching (a test that I didn't think of) and because the call to AAD wouldn't throw an exception in this case, we end up with this error.

**Comment by peterfelts** [comment]
I created pull #44 to hopefully catch this case and output an error message. I wasn't able to repro the issue on my end though. I removed the app admin role for my account and ran a deployment but, for me, the call to AAD to register the app threw an exception, as expected. I don't understand why the app registration is apparently failing without the Graph API client throwing. 

Please pull the code from pull #44 and see if you receive the new error (that would at least tell us that AAD app registration is failing for sure).

**Comment by shivanjalikhare** [comment]
> I created pull #44 to hopefully catch this case and output an error message. I wasn't able to repro the issue on my end though. I removed the app admin role for my account and ran a deployment but, for me, the call to AAD to register the app threw an exception, as expected. I don't understand why the app registration is apparently failing without the Graph API client throwing.
> 
> Please pull the code from pull #44 and see if you receive the new error (that would at least tell us that AAD app registration is failing for sure).

Hello, I pulled your code and got the new error (as you mentioned). I was again getting few errors but I solved them by changing the node.js version. The workspace was somehow taking the older version of it. So now everything is set. 
Thanks!
