### ISSUE TITLE
Error in docker compose file for storage adapter

### ISSUE THREAD

**Issue by jeco1996** [Azure/azure-iot-pcs-device-simulation#46]
# Type of issue 

- [x ] Bug
- [ ] New feature
- [ ] Enhancement

# Description 

ERROR: In file '.\docker-compose.yml', service must be a mapping, not a NoneType.
...

# Steps to reproduce 
1. When doing docker-compose up on windows 10, I get this error about docker
2
ERROR: In file '.\docker-compose.yml', service must be a mapping, not a NoneType.

**Comment by pratik11jain** [comment]
Hi, Can you please give more information about what operation you are trying to perform and how?
It looks like you need to follow https://github.com/Azure/azure-iot-pcs-device-simulation/blob/master/deployment/README.md to do a deployment

**Comment by jeco1996** [comment]
Hi, so it seems following those steps don't run the proyect, so my guess is that you need to manually run each microservice for it to work right?

So After trying to do that, the docker compose for the storage  adapter is not working.


it says the following: ERROR: In file '.\docker-compose.yml', service must be a mapping, not a NoneType.

**Comment by jeco1996** [comment]
Hi, so it seems following those steps don't run the proyect, so my guess is
that you need to manually run each microservice for it to work right?

So After trying to do that, the docker compose for the storage  adapter is
not working.


it says the following: ERROR: In file '.\docker-compose.yml', service must
be a mapping, not a NoneType.
[image: image.png]

**Comment by scottcun** [comment]
The supported way to run a simulation is to follow the steps under  `[deployment/README.md](https://github.com/Azure/azure-iot-pcs-device-simulation/blob/master/deployment/README.md).`  If you follow these steps, upon completion of running `npm run deploy`, you will get two URL's like shown below:

``` sh
R:\github\Azure\azure-iot-pcs-device-simulation\deployment>npm run deploy

...
<REMOVED FOR BREVITY>
...
Latest state = Running
Latest state = Running
Latest state = Running
Latest state = Succeeded
Deployment Succeeded.
>> You can access the Simulation website here: **https://<SOLUTION-NAME>.azurewebsites.net**
>> You can access the deployed Azure resources here: **https://portal.azure.com/<TENANT-ID>#resource/subscriptions/<SUBSCRIPTION-ID>/resourceGroups/<SOLUTION-NAME>**
```
With the first URL above, you can access the Simulation website for your deployment, allowing you to create and operate simulations.

You should not need to manually perform a docker compose.  While theoretically you could use docker compose to locally run the microservices, this approach has not been tested and is not supported.

**Comment by jeco1996** [comment]
Thanks
